# /var/www/nexus-gear-store/docker-compose.yml - ФИНАЛЬНАЯ ВЕРСИЯ

services:
  bot:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "8081:8080"
    # --- ИЗМЕНЕНИЕ: Убираем явное указание сети ---
    # networks:
    #   - nexus_gear_network

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB__USER}
      - POSTGRES_PASSWORD=${DB__PASSWORD}
      - POSTGRES_DB=${DB__NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # --- ИЗМЕНЕНИЕ: Убираем явное указание сети ---
    # networks:
    #   - nexus_gear_network

volumes:
  postgres_data:

# --- ИЗМЕНЕНИЕ: Полностью удаляем секцию networks ---
# networks:
#   nexus_gear_network:
#     driver: bridge