services:
  bot:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    networks:
      - nexus_store_net

  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      # --- ИЗМЕНЕНИЕ ЗДЕСЬ ---
      # Используем наш новый, уникально именованный том
      - nexus_store_pg_data:/var/lib/postgresql/data
    networks:
      - nexus_store_net

# --- ИЗМЕНЕНИЕ ЗДЕСЬ ---
# Определяем наш новый, уникально именованный том
volumes:
  nexus_store_pg_data:

networks:
  nexus_store_net:
    driver: bridge