[tool.poetry]
name = "nexus-gear-store"
version = "0.1.0"
description = "Telegram bot store 'NEXUS Gear'"
authors = ["AI Orchestrator <you@example.com>"]
readme = "README.md"
packages = [{include = "nexus_gear_store", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
aiogram = "^3.7.0"
aiohttp = "^3.9.5"
sqlalchemy = {extras = ["asyncio"], version = "^2.0.31"}
asyncpg = "^0.29.0"
alembic = "^1.13.1"
pydantic = "^2.8.2"
pydantic-settings = "^2.3.4"
python-dotenv = "^1.0.1"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.2"
pytest-asyncio = "^0.23.7"
black = "^24.4.2"
isort = "^5.13.2"
flake8 = "^7.1.0"
mypy = "^1.10.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
