name: Docker Build & Publish

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.py'
      - 'vue-project/**'
      - 'Dockerfile'
      - '.github/workflows/docker.yml'
  pull_request:
    paths:
      - '**/*.py'
      - 'vue-project/**'
      - 'Dockerfile'

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node 20 (build dist for artifact)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: vue-project/package-lock.json

      - name: Install deps (frontend)
        working-directory: vue-project
        run: npm ci --no-audit --no-fund

      - name: Build (frontend)
        working-directory: vue-project
        run: npm run build

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: vue-project/dist
          if-no-files-found: error

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/${{ github.repository }}:sha-${{ github.sha }}
            ghcr.io/${{ github.repository }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max


